[theme]
base="dark"
primaryColor = "#00C49A"
backgroundColor = "#121212"
secondaryBackgroundColor = "#1E1E1E"
textColor = "#F1F1F1"
headingFont = "monospace"
[theme.sidebar]
font = "monospace"
backgroundColor = "#00C49A"